version: "3"
networks:
  local_net:
    driver: bridge

services:
  client:
    container_name: client
    image: index.docker.io/orderr66/client:latest
    depends_on:
      - server
      - neo4j
    ports:
      - '8080:8080'
    networks:
      - local_net
  server:
    container_name: server
    image: index.docker.io/orderr66/server:latest
    command: "npm run clear-nodes-prod && npm run migrate-prod"
    restart: on-failure
    env_file:
      - .env
    depends_on:
      - neo4j
    ports:
      - "4000:4000"
    networks:
      - local_net
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./conf:/conf
      - ./data:/data
      - ./import:/import
      - ./logs:/logs
      - ./plugins:/plugins
    environment:
      - NEO4J_dbms_allow__upgrade=true
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_AUTH=neo4j/test
    networks:
      - local_net