name: Build Containers for Prod & Push to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy-back:
    name: Build and Deploy Server
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: orderr66/server
        dockerfile: server/Dockerfile
        tags: latest

  build-and-deploy-front:
    name: Build and Deploy Client
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: orderr66/client
        dockerfile: client/Dockerfile
        tags: latest
